spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: web
          uri: lb://my-customer
          predicates:
            - Path=/api-web/**
          filters:
            - StripPrefix=1